"""
This type stub file was generated by pyright.
"""

from .typing import ColorType

BASE_COLORS: dict[str, ColorType]
TABLEAU_COLORS: dict[str, ColorType]
XKCD_COLORS: dict[str, ColorType]
CSS4_COLORS: dict[str, ColorType]
