"""
This type stub file was generated by pyright.
"""

import numpy as np
from collections.abc import Sequence
from .transforms import BboxBase

def affine_transform(points: np.ndarray, trans: np.ndarray) -> np.ndarray:
    ...

def count_bboxes_overlapping_bbox(bbox: BboxBase, bboxes: Sequence[BboxBase]) -> int:
    ...

def update_path_extents(path, trans, rect, minpos, ignore):
    ...

